# Generated by Django 5.1.1 on 2024-09-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_grader', '0003_assignment_description_assignment_last_retrieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
