# Generated by Django 5.1.1 on 2024-09-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_grader', '0004_alter_submission_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
