# Generated by Django 5.1.1 on 2024-09-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_grader', '0005_alter_submission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.TextField(blank=True, null=True),
        ),
    ]
