# Generated by Django 5.1.1 on 2024-09-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_grader', '0006_assignment_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student_nid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
