# Generated by Django 5.1.1 on 2025-08-08 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_grader', '0008_platform_assignment_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.IntegerField()),
                ('short_description', models.CharField(max_length=200)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_grades', to='auto_grader.assignment')),
            ],
            options={
                'ordering': ['grade_number'],
                'unique_together': {('assignment', 'grade_number')},
            },
        ),
    ]
