# Generated by Django 5.1.1 on 2025-08-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_grader', '0009_rubricgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('graded', 'Graded'), ('error', 'Error')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
